# Generated by Django 4.2.23 on 2025-10-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='application',
            name='product',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quantity_packages',
        ),
        migrations.CreateModel(
            name='ApplicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_packages', models.FloatField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='application.application')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.presentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
