# Generated by Django 4.2.23 on 2025-10-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetail',
            name='presentation',
        ),
    ]
