# Generated by Django 4.2.23 on 2025-11-07 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_equipment_codigo_interno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_is_active'),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='applicationdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
