-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.application_application
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    applied_at timestamp with time zone NOT NULL,
    applied_by_id integer,
    equipment_id bigint,
    sector_id bigint,
    ware_id bigint NOT NULL,
    CONSTRAINT application_application_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.application_applicationdetail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quantity_packages double precision NOT NULL,
    application_id bigint NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT application_applicationdetail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_apscheduler_djangojob
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    next_run_time timestamp with time zone,
    job_state bytea NOT NULL,
    CONSTRAINT django_apscheduler_djangojob_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_apscheduler_djangojobexecution
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    run_time timestamp with time zone NOT NULL,
    duration numeric(15, 2),
    finished numeric(15, 2),
    exception character varying(1000) COLLATE pg_catalog."default",
    traceback text COLLATE pg_catalog."default",
    job_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_apscheduler_djangojobexecution_pkey PRIMARY KEY (id),
    CONSTRAINT unique_job_executions UNIQUE (job_id, run_time)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.login_role
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name_role character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description_role text COLLATE pg_catalog."default",
    CONSTRAINT login_role_pkey PRIMARY KEY (id),
    CONSTRAINT login_role_name_role_key UNIQUE (name_role)
);

CREATE TABLE IF NOT EXISTS public.login_userrole
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT login_userrole_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.login_usuario
(
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id_user integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_usuario character varying(150) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    correo character varying(254) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    must_change_password boolean NOT NULL,
    CONSTRAINT login_usuario_pkey PRIMARY KEY (id_user),
    CONSTRAINT login_usuario_correo_key UNIQUE (correo),
    CONSTRAINT login_usuario_nombre_usuario_key UNIQUE (nombre_usuario)
);

CREATE TABLE IF NOT EXISTS public.login_usuario_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT login_usuario_groups_pkey PRIMARY KEY (id),
    CONSTRAINT login_usuario_groups_usuario_id_group_id_735946fe_uniq UNIQUE (usuario_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.login_usuario_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT login_usuario_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT login_usuario_user_permi_usuario_id_permission_id_8ca7a3fc_uniq UNIQUE (usuario_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.login_usuario_ware_assig
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    usuario_id integer NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT login_usuario_casetas_asignadas_pkey PRIMARY KEY (id),
    CONSTRAINT login_usuario_casetas_as_usuario_id_warehouse_id_04744a60_uniq UNIQUE (usuario_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS public.notification_notification
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    notif_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    read boolean NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    product_id integer NOT NULL,
    user_id integer NOT NULL,
    warehouse_id bigint,
    CONSTRAINT notification_notification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_category
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name_cat character varying(120) COLLATE pg_catalog."default" NOT NULL,
    description_cat text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT product_category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.product_presentation
(
    presentation_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    package_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    content_value double precision NOT NULL,
    content_unit character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT product_presentation_pkey PRIMARY KEY (presentation_id)
);

CREATE TABLE IF NOT EXISTS public.product_product
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name_prod character varying(120) COLLATE pg_catalog."default" NOT NULL,
    added_at timestamp with time zone NOT NULL,
    expire_at timestamp with time zone NOT NULL,
    category_id integer NOT NULL,
    presentation_id integer NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT product_product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.warehouse_equipment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre_equipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    codigo_interno character varying(20) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    activo boolean NOT NULL,
    caseta_id bigint NOT NULL,
    CONSTRAINT warehouse_equipment_pkey PRIMARY KEY (id),
    CONSTRAINT warehouse_equipment_caseta_id_nombre_equipo_c24306e4_uniq UNIQUE (caseta_id, nombre_equipo)
);

CREATE TABLE IF NOT EXISTS public.warehouse_inventory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    quantity_packages double precision NOT NULL,
    total_content double precision NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    presentation_id integer NOT NULL,
    product_id integer NOT NULL,
    warehouse_id bigint NOT NULL,
    CONSTRAINT warehouse_inventory_pkey PRIMARY KEY (id),
    CONSTRAINT warehouse_inventory_product_id_presentation__3148729f_uniq UNIQUE (product_id, presentation_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS public.warehouse_movement
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    movement_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    quantity double precision NOT NULL,
    moved_at timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default",
    moved_by_id integer,
    presentation_id integer NOT NULL,
    product_id integer NOT NULL,
    ware_destin_id bigint,
    ware_origin_id bigint,
    CONSTRAINT warehouse_movement_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.warehouse_sector
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sector_num integer NOT NULL,
    observaciones text COLLATE pg_catalog."default",
    equipment_id bigint NOT NULL,
    CONSTRAINT warehouse_sector_pkey PRIMARY KEY (id),
    CONSTRAINT warehouse_sector_equipment_id_sector_num_e48624dc_uniq UNIQUE (equipment_id, sector_num)
);

CREATE TABLE IF NOT EXISTS public.warehouse_warehouse
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name_ware character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT warehouse_warehouse_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.application_application
    ADD CONSTRAINT application_applicat_applied_by_id_bf3e4e7d_fk_login_usu FOREIGN KEY (applied_by_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS application_application_applied_by_id_bf3e4e7d
    ON public.application_application(applied_by_id);


ALTER TABLE IF EXISTS public.application_application
    ADD CONSTRAINT application_applicat_equipment_id_67dcd7ff_fk_warehouse FOREIGN KEY (equipment_id)
    REFERENCES public.warehouse_equipment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS application_application_equipment_id_67dcd7ff
    ON public.application_application(equipment_id);


ALTER TABLE IF EXISTS public.application_application
    ADD CONSTRAINT application_applicat_sector_id_a38b60e7_fk_warehouse FOREIGN KEY (sector_id)
    REFERENCES public.warehouse_sector (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS application_application_sector_id_a38b60e7
    ON public.application_application(sector_id);


ALTER TABLE IF EXISTS public.application_application
    ADD CONSTRAINT application_applicat_ware_id_783f818c_fk_warehouse FOREIGN KEY (ware_id)
    REFERENCES public.warehouse_warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS application_application_ware_id_783f818c
    ON public.application_application(ware_id);


ALTER TABLE IF EXISTS public.application_applicationdetail
    ADD CONSTRAINT application_applicat_application_id_18759669_fk_applicati FOREIGN KEY (application_id)
    REFERENCES public.application_application (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS application_applicationdetail_application_id_18759669
    ON public.application_applicationdetail(application_id);


ALTER TABLE IF EXISTS public.application_applicationdetail
    ADD CONSTRAINT application_applicat_product_id_8965c48c_fk_product_p FOREIGN KEY (product_id)
    REFERENCES public.product_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS application_applicationdetail_product_id_8965c48c
    ON public.application_applicationdetail(product_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_login_usuario_id_user FOREIGN KEY (user_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT django_apscheduler_djangojobexecution_job_id_daf5090a_fk FOREIGN KEY (job_id)
    REFERENCES public.django_apscheduler_djangojob (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_apscheduler_djangojobexecution_job_id_daf5090a
    ON public.django_apscheduler_djangojobexecution(job_id);


ALTER TABLE IF EXISTS public.login_userrole
    ADD CONSTRAINT login_userrole_role_id_0f43b711_fk_login_role_id FOREIGN KEY (role_id)
    REFERENCES public.login_role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_userrole_role_id_0f43b711
    ON public.login_userrole(role_id);


ALTER TABLE IF EXISTS public.login_userrole
    ADD CONSTRAINT login_userrole_user_id_499a7746_fk_login_usuario_id_user FOREIGN KEY (user_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_userrole_user_id_499a7746
    ON public.login_userrole(user_id);


ALTER TABLE IF EXISTS public.login_usuario_groups
    ADD CONSTRAINT login_usuario_groups_group_id_e38af65c_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_usuario_groups_group_id_e38af65c
    ON public.login_usuario_groups(group_id);


ALTER TABLE IF EXISTS public.login_usuario_groups
    ADD CONSTRAINT login_usuario_groups_usuario_id_ac4f2bc2_fk_login_usu FOREIGN KEY (usuario_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_usuario_groups_usuario_id_ac4f2bc2
    ON public.login_usuario_groups(usuario_id);


ALTER TABLE IF EXISTS public.login_usuario_user_permissions
    ADD CONSTRAINT login_usuario_user_p_permission_id_a3c8199c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_usuario_user_permissions_permission_id_a3c8199c
    ON public.login_usuario_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.login_usuario_user_permissions
    ADD CONSTRAINT login_usuario_user_p_usuario_id_0ae58d2f_fk_login_usu FOREIGN KEY (usuario_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_usuario_user_permissions_usuario_id_0ae58d2f
    ON public.login_usuario_user_permissions(usuario_id);


ALTER TABLE IF EXISTS public.login_usuario_ware_assig
    ADD CONSTRAINT login_usuario_caseta_usuario_id_eff007a0_fk_login_usu FOREIGN KEY (usuario_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_usuario_casetas_asignadas_usuario_id_eff007a0
    ON public.login_usuario_ware_assig(usuario_id);


ALTER TABLE IF EXISTS public.login_usuario_ware_assig
    ADD CONSTRAINT login_usuario_caseta_warehouse_id_36335970_fk_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouse_warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS login_usuario_casetas_asignadas_warehouse_id_36335970
    ON public.login_usuario_ware_assig(warehouse_id);


ALTER TABLE IF EXISTS public.notification_notification
    ADD CONSTRAINT notification_notific_product_id_abc29bb3_fk_product_p FOREIGN KEY (product_id)
    REFERENCES public.product_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS notification_notification_product_id_abc29bb3
    ON public.notification_notification(product_id);


ALTER TABLE IF EXISTS public.notification_notification
    ADD CONSTRAINT notification_notific_user_id_e9d6f5f4_fk_login_usu FOREIGN KEY (user_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS notification_notification_user_id_e9d6f5f4
    ON public.notification_notification(user_id);


ALTER TABLE IF EXISTS public.notification_notification
    ADD CONSTRAINT notification_notific_warehouse_id_a0b0bd09_fk_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouse_inventory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS notification_notification_warehouse_id_a0b0bd09
    ON public.notification_notification(warehouse_id);


ALTER TABLE IF EXISTS public.product_product
    ADD CONSTRAINT product_product_category_id_0c725779_fk_product_c FOREIGN KEY (category_id)
    REFERENCES public.product_category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS product_product_category_id_0c725779
    ON public.product_product(category_id);


ALTER TABLE IF EXISTS public.product_product
    ADD CONSTRAINT product_product_presentation_id_357f7094_fk_product_p FOREIGN KEY (presentation_id)
    REFERENCES public.product_presentation (presentation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS product_product_presentation_id_357f7094
    ON public.product_product(presentation_id);


ALTER TABLE IF EXISTS public.warehouse_equipment
    ADD CONSTRAINT warehouse_equipment_caseta_id_7fde33f9_fk_warehouse FOREIGN KEY (caseta_id)
    REFERENCES public.warehouse_warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_equipment_caseta_id_7fde33f9
    ON public.warehouse_equipment(caseta_id);


ALTER TABLE IF EXISTS public.warehouse_inventory
    ADD CONSTRAINT warehouse_inventory_presentation_id_017dbf16_fk_product_p FOREIGN KEY (presentation_id)
    REFERENCES public.product_presentation (presentation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_inventory_presentation_id_017dbf16
    ON public.warehouse_inventory(presentation_id);


ALTER TABLE IF EXISTS public.warehouse_inventory
    ADD CONSTRAINT warehouse_inventory_product_id_cae4e192_fk_product_p FOREIGN KEY (product_id)
    REFERENCES public.product_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_inventory_product_id_cae4e192
    ON public.warehouse_inventory(product_id);


ALTER TABLE IF EXISTS public.warehouse_inventory
    ADD CONSTRAINT warehouse_inventory_warehouse_id_502d821d_fk_warehouse FOREIGN KEY (warehouse_id)
    REFERENCES public.warehouse_warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_inventory_warehouse_id_502d821d
    ON public.warehouse_inventory(warehouse_id);


ALTER TABLE IF EXISTS public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_moved_by_id_31e0c5b2_fk_login_usu FOREIGN KEY (moved_by_id)
    REFERENCES public.login_usuario (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_movement_moved_by_id_31e0c5b2
    ON public.warehouse_movement(moved_by_id);


ALTER TABLE IF EXISTS public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_presentation_id_9a24fb95_fk_product_p FOREIGN KEY (presentation_id)
    REFERENCES public.product_presentation (presentation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_movement_presentation_id_9a24fb95
    ON public.warehouse_movement(presentation_id);


ALTER TABLE IF EXISTS public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_product_id_aa7fd1e0_fk_product_p FOREIGN KEY (product_id)
    REFERENCES public.product_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_movement_product_id_aa7fd1e0
    ON public.warehouse_movement(product_id);


ALTER TABLE IF EXISTS public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_ware_destin_id_8badf497_fk_warehouse FOREIGN KEY (ware_destin_id)
    REFERENCES public.warehouse_warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_movement_ware_destin_id_8badf497
    ON public.warehouse_movement(ware_destin_id);


ALTER TABLE IF EXISTS public.warehouse_movement
    ADD CONSTRAINT warehouse_movement_ware_origin_id_9743f368_fk_warehouse FOREIGN KEY (ware_origin_id)
    REFERENCES public.warehouse_warehouse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_movement_ware_origin_id_9743f368
    ON public.warehouse_movement(ware_origin_id);


ALTER TABLE IF EXISTS public.warehouse_sector
    ADD CONSTRAINT warehouse_sector_equipment_id_8d2dd7d2_fk_warehouse FOREIGN KEY (equipment_id)
    REFERENCES public.warehouse_equipment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warehouse_sector_equipment_id_8d2dd7d2
    ON public.warehouse_sector(equipment_id);

END;
