# Generated by Django 4.2.23 on 2025-10-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='login.UserRole', to='login.role'),
        ),
    ]
