# Generated by Django 4.2.23 on 2025-11-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("warehouse", "0001_initial"),
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ware_assig",
            field=models.ManyToManyField(
                blank=True,
                help_text="Casetas asignadas (solo aplica para Encargados de caseta)",
                limit_choices_to={"type": "shed"},
                related_name="encargados_multiples",
                to="warehouse.warehouse",
            ),
        ),
    ]
