# Generated by Django 4.2.23 on 2025-10-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
        ("login", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="caseta_asignada",
        ),
        migrations.AddField(
            model_name="usuario",
            name="casetas_asignadas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Casetas asignadas (solo aplica para Encargados de caseta)",
                limit_choices_to={"type": "shed"},
                related_name="encargados_multiples",
                to="warehouse.warehouse",
            ),
        ),
    ]
