# Generated by Django 4.2.23 on 2025-10-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuario_roles'),
    ]

    operations = [
            migrations.RenameField(
            model_name='usuario',
            old_name='roles',
            new_name='role',
        ),
    ]
