# Generated by Django 4.2.23 on 2025-11-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_usuario_caseta_asignada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='casetas_asignadas',
            new_name='ware_assig',
        ),
    ]
