# Generated by Django 4.2.23 on 2025-10-03 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20251003_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='role',
            new_name='roles',
        ),
    ]
