# Generated by Django 4.2.23 on 2025-10-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_cat', models.CharField(max_length=120)),
                ('description_cat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CATEGORY',
                'ordering': ['name_cat'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_prod', models.CharField(max_length=120)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category')),
            ],
            options={
                'db_table': 'PRODUCT',
                'ordering': ['name_prod'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('saco', 'Saco'), ('bidon', 'Bidón'), ('caja', 'Caja'), ('paquete', 'Paquete')], max_length=10)),
                ('content_value', models.FloatField()),
                ('content_unit', models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros')], max_length=10)),
                ('stock_units', models.PositiveIntegerField(default=0, help_text='Número de envases disponibles', verbose_name='Unidades en stock')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='product.product')),
            ],
            options={
                'db_table': 'PRESENTATION',
                'ordering': ['product__name_prod', 'package_type'],
            },
        ),
    ]
