# Generated by Django 4.2.23 on 2025-10-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_cat", models.CharField(max_length=120)),
                ("description_cat", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name_cat"],
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "presentation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("saco", "Saco"),
                            ("bidon", "Bidón"),
                            ("caja", "Caja"),
                            ("paquete", "Paquete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content_value", models.FloatField()),
                (
                    "content_unit",
                    models.CharField(
                        choices=[("kg", "Kilogramos"), ("litros", "Litros")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["package_type", "content_value"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("name_prod", models.CharField(max_length=120)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("expire_at", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="product.category",
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="product.presentation",
                    ),
                ),
            ],
            options={
                "ordering": ["name_prod"],
            },
        ),
    ]
