# Generated by Django 4.2.23 on 2025-10-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='stock_units',
        ),
    ]
