# Generated by Django 5.2.6 on 2025-09-26 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_caseta_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_cat', models.CharField(max_length=120)),
                ('description_cat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CATEGORY',
                'ordering': ['name_cat'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('presentation_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('sack', 'Sack'), ('drum', 'Drum'), ('box', 'Box'), ('package', 'Package')], max_length=10)),
                ('content_value', models.FloatField()),
                ('content_unit', models.CharField(choices=[('kg', 'Kilograms'), ('liters', 'Liters')], max_length=10)),
            ],
            options={
                'db_table': 'PRESENTATION',
                'ordering': ['product__name_prod', 'package_type'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_prod', models.CharField(max_length=120)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category')),
            ],
            options={
                'db_table': 'PRODUCT',
                'ordering': ['name_prod'],
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='presentation',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='core.product'),
        ),
    ]
