# Generated by Django 5.2.6 on 2025-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_presentation_product_delete_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='stock_units',
            field=models.PositiveIntegerField(default=0, help_text='Número de envases disponibles', verbose_name='Unidades en stock'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='content_unit',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='package_type',
            field=models.CharField(choices=[('saco', 'Saco'), ('bidon', 'Bidón'), ('caja', 'Caja'), ('paquete', 'Paquete')], max_length=10),
        ),
    ]
