# Generated by Django 4.2.23 on 2025-11-13 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("application", "Aplicaciones"),
                            ("warehouse", "Casetas / Inventario"),
                            ("product", "Productos"),
                            ("notification", "Notificaciones"),
                            ("reports", "Reportes"),
                            ("other", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=100, verbose_name="Asunto")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_review", "En Revisión"),
                            ("resolved", "Resuelto"),
                            ("closed", "Cerrado"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Comentario del administrador",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de problema",
                "verbose_name_plural": "Reportes de problemas",
                "ordering": ["-created_at"],
            },
        ),
    ]
