# Generated by Django 4.2.23 on 2025-11-10 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaReportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto del problema')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_problema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problema Reportado',
                'verbose_name_plural': 'Problemas Reportados',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
