# Generated by Django 4.2.23 on 2025-11-10 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('application', 'Aplicaciones'), ('warehouse', 'Casetas / Inventario'), ('product', 'Productos'), ('notification', 'Notificaciones'), ('reports', 'Reportes'), ('other', 'Otro')], max_length=30)),
                ('description', models.TextField(verbose_name='Descripción del problema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En Revisión'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='pending', max_length=15)),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Comentario del administrador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de problema',
                'verbose_name_plural': 'Reportes de problemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProblemaReportado',
        ),
    ]
