# Generated by Django 4.2.23 on 2025-11-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_problemreport_delete_problemareportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemreport',
            name='priority',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='problemreport',
            name='subject',
            field=models.CharField(default=0.041666666666666664, max_length=100, verbose_name='Asunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
