# Generated by Django 4.2.23 on 2025-11-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ware', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('main', 'Bodega Principal'), ('shed', 'Caseta')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('traslado', 'Traslado')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.presentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('ware_destin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_destin', to='warehouse.warehouse')),
                ('ware_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_origin', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(help_text="Nombre del equipo (Ej: 'A Cítricos', 'Equipo 2', 'Paltos A')", max_length=50)),
                ('codigo_interno', models.CharField(blank=True, help_text='Código opcional interno o alias corto del equipo', max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('caseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['caseta__name_ware', 'nombre_equipo'],
                'unique_together': {('caseta', 'nombre_equipo')},
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_num', models.PositiveIntegerField(help_text='Número de sector dentro del equipo')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='warehouse.equipment')),
            ],
            options={
                'ordering': ['equipment__nombre_equipo', 'sector_num'],
                'unique_together': {('equipment', 'sector_num')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_packages', models.FloatField(default=0)),
                ('total_content', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.presentation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'unique_together': {('product', 'presentation', 'warehouse')},
            },
        ),
    ]
