# Generated by Django 4.2.23 on 2025-10-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_content',
            field=models.FloatField(default=0),
        ),
    ]
