# Generated by Django 4.2.23 on 2025-11-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='nombre_equipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.presentation'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('traslado', 'Traslado'), ('salida', 'Salida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movement',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.presentation'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movement',
            name='ware_destin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_destin', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_num',
            field=models.PositiveIntegerField(),
        ),
    ]
