# Generated by Django 4.2.23 on 2025-10-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
