# Generated by Django 4.2.24 on 2025-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name_ware',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('main', 'Bodega Principal'), ('shed', 'Caseta')], max_length=50),
        ),
    ]
