# Generated by Django 4.2.23 on 2025-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_equipment_codigo_interno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
