# Generated by Django 4.2.24 on 2025-10-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('warehouse', '0002_alter_warehouse_name_ware_alter_warehouse_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventorySummary',
            new_name='Inventory',
        ),
    ]
