# Generated by Django 4.2.24 on 2025-10-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_rename_inventorysummary_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='moved_by',
            field=models.IntegerField(),
        ),
    ]
