# Generated by Django 4.2.24 on 2025-10-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('warehouse', '0004_alter_movement_moved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='ware',
            new_name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'presentation', 'warehouse')},
        ),
    ]
